services:
  app:
    build: .
    container_name: ssgfinance-app
    restart: unless-stopped
    network_mode: host

    env_file:
      - .env

    environment:
      ASPNETCORE_ENVIRONMENT: Production

    volumes:
      - "${HOME}/uploads:/app/wwwroot/uploads"
