services:
  app:
    build: .
    container_name: ssgfinance-app
    restart: unless-stopped

    env_file:
      - .env

    environment:
      ASPNETCORE_ENVIRONMENT: Production
      ASPNETCORE_URLS: http://+:${PORT:-3000}

    expose:
      - "${PORT:-3000}"

    volumes:
      - uploads:/app/wwwroot/uploads

    networks:
      - ssgfinance-network
      - proxy-network

volumes:
  uploads:

networks:
  ssgfinance-network:
    external: true

  proxy-network:
    external: true
